### ISSUE TITLE
getComments(url) doesn't provide author information on comments field

### ISSUE THREAD

**Issue by ozanilbey** [pho-incubator/graphjs-server#19]

**Comment by ozanilbey** [comment]
Sample query: http://phonetworks.com:1338/getComments?url=http://localhost:8080/docs.html??&public_id=16D58CF2-FD88-4A49-972B-6F60054BF023

**Comment by esokullu** [comment]
Done, you probably need avatar info too, right? Avatar etc. What else?

**Comment by ozanilbey** [comment]
It works!
