### ISSUE TITLE
unstar(url) is buggy

### ISSUE THREAD

**Issue by ozanilbey** [pho-incubator/graphjs-server#20]
Request: http://phonetworks.com:1338/unstar?url=http://localhost:8080/docs.html???&public_id=16D58CF2-FD88-4A49-972B-6F60054BF023
Response: PhoNetworksAutogenerated\UserOut\Star is not multiplicable and there's already an edge from 4b688921975b3f46544c487d268e24d6 to 54a26ffcaf7a36c3aa0161ccd4317b78

**Comment by esokullu** [comment]
Same as #15 closing.
