### ISSUE TITLE
isStarred encounters a problem for a specific url

### ISSUE THREAD

**Issue by ozanilbey** [pho-incubator/graphjs-server#21]
This is probably because of the old data.

Request: http://phonetworks.com:1338/isStarred?url=http://localhost:8080/docs.html&public_id=16D58CF2-FD88-4A49-972B-6F60054BF023
Response: There is no node registered with the uuid 50cb927975c88399f3c59951691e0323.

**Comment by ozanilbey** [comment]
getComments has the same issue for the same exact URL

**Comment by esokullu** [comment]
same as #15 closing
