### ISSUE TITLE
getGroup(id) call is needed

### ISSUE THREAD

**Issue by ozanilbey** [pho-incubator/graphjs-server#25]
There is no available option to show group details

**Comment by esokullu** [comment]
listGroups already gives you all the details you need. Plus, when inside, you can use listMemberships to fetch all their members.

**Comment by ozanilbey** [comment]
getGroup(id) is neccessary to list any user's groups. Without this we have to listGroups, then listMembers of each group, then check if a specific user belongs to that group.

**Comment by esokullu** [comment]
listMemberships not listMembers.

**Comment by esokullu** [comment]
you can easily cache the

**Comment by ozanilbey** [comment]
listMemberships list the groups of signed user

**Comment by esokullu** [comment]
Sorry you're right, it's listMembers but when you search listMembers with a group id, it gives you its members. Other info can be cached from the previous step since you get to the groups from listMembers anyway. Don't you?

**Comment by ozanilbey** [comment]
Not quite like that, actually. I use this function on Profile to show profile owner's groups. Not using any of the mentioned functions.

**Comment by ozanilbey** [comment]
It's just like getFollowers or getFollowing. It helps me to list user's relations with other nodes.

**Comment by esokullu** [comment]
You may try with http://phonetworks.com:1338/getGroup?id=%id%

**Comment by ozanilbey** [comment]
Request: http://phonetworks.com:1338/getGroup?id=4b688921975b3f46544c487d268e24d6&public_id=16D58CF2-FD88-4A49-972B-6F60054BF023
Response: The particle Pho\Framework\Handlers\Gateway was called with the invalid method: members

After the last commit (seconds ago).

**Comment by ozanilbey** [comment]
You are right! Sorry for that. Closing this one.
