### ISSUE TITLE
Character problem in getStarredContent

### ISSUE THREAD

**Issue by ozanilbey** [pho-incubator/graphjs-server#26]
...and probably getMyStarredContent. Couldn't test because server is not responding anymore.

Sample: `H&#252;rriyet - Haberler, Son Dakika Haberleri ve G&#252;ncel Haber`

**Comment by ozanilbey** [comment]
It's better to store and deliver our data in UTF-8 format.

**Comment by ozanilbey** [comment]
Server is responding. I tested getMyStarredContent.

Sample: `M\u0130LL\u0130YET HABER - Haberler - Son Dakika Haberleri` (different encoding)

**Comment by esokullu** [comment]
Use ```unescape``` it should work properly.

**Comment by ozanilbey** [comment]
Worked for getMyStarredContent but not for getStarredContent

**Comment by esokullu** [comment]
```escape``` is a universal function, it would be weird that it works in one place, and doesn't in another. Send me the examples where you see it won't work.

**Comment by ozanilbey** [comment]
Listed results with different encoding above. Will provide the request links soon.

**Comment by ozanilbey** [comment]
- http://phonetworks.com:1338/getStarredContent?public_id=16D58CF2-FD88-4A49-972B-6F60054BF023

- http://phonetworks.com:1338/getMyStarredContent?public_id=16D58CF2-FD88-4A49-972B-6F60054BF023

**Comment by esokullu** [comment]
fixed in https://github.com/pho-incubator/graphjs-server/commit/6f4d77a0369adb170ef32d3be31a3ea5c183b09c
