### ISSUE TITLE
is_read field on getConversations should be updated upon getConversation(with)

### ISSUE THREAD

**Issue by ozanilbey** [pho-incubator/graphjs-server#3]

**Comment by esokullu** [comment]
The code seems ok.

``` "MATCH (:user {udid: {u1}})-[r:message]-(:user {udid: {u2}}) SET r.IsRead = true RETURN startNode(r).udid as t, r ORDER BY r.SentTime DESC",```

Please make sure it's not a cache issue. Try adding a random id at the end of each query (a new set of parameters like &randid=%randid%)

**Comment by ozanilbey** [comment]
Tested as you asked. The field "is_read" in getConversation*s* never gets updated.

**Comment by esokullu** [comment]
ok can you send me the queries.

**Comment by ozanilbey** [comment]
Firstly, I fetch conversations: http://phonetworks.com:1338/getConversations?public_id=16D58CF2-FD88-4A49-972B-6F60054BF023

You can see that all the "is_read" fields are "false". 

Then I fetch conversation with someone, let's say 4a727c202b9060f0b0a940a2a0074518: http://phonetworks.com:1338/getConversation?with=4a727c202b9060f0b0a940a2a0074518&public_id=16D58CF2-FD88-4A49-972B-6F60054BF023

That makes "is_read" field "true" on this call (getConversation).

Let's check if getConversation*s* updated... : http://phonetworks.com:1338/getConversations?public_id=16D58CF2-FD88-4A49-972B-6F60054BF023 

Not updated.

**Comment by esokullu** [comment]
related to: #16

**Comment by esokullu** [comment]
This may have been fixed.
