### ISSUE TITLE
fullname or displayname field would be good on setProfile and get Profile

### ISSUE THREAD

**Issue by ozanilbey** [pho-incubator/graphjs-server#4]
It can be optional. Sometimes, this could create a better option. For example, a social network for lawyers would seem better with formal names.

**Comment by esokullu** [comment]
https://screencast.com/t/7jw3KzIempuI

**Comment by esokullu** [comment]
Yapilan sey su, gene username, ancak bosluk koyabiliyorsun ve 36 karaktere kadar cikabiliyorsun. Bir de sanirim butun unicode karakterleri desteklememiz lazim, su an ASCII-only.

**Comment by ozanilbey** [comment]
Closing this for now. Graph.js will continue with "username" as nothing ever changed.
