### ISSUE TITLE
getProfile should return a field named "groups" including group ids

### ISSUE THREAD

**Issue by ozanilbey** [pho-incubator/graphjs-server#6]
or something like listMemberships(user)

**Comment by esokullu** [comment]
Can't you get this with a separate call?

**Comment by ozanilbey** [comment]
I can do it with something like listMemberships(user) but there isn't any available right now.

**Comment by esokullu** [comment]
What about /listGroups

**Comment by ozanilbey** [comment]
As far as I know, listGroups is not user-specific. I need something user-specific.

**Comment by ozanilbey** [comment]
Freshly implemented listMemberships(id) call works!
