### ISSUE TITLE
There is a "unique username" problem with setProfile

### ISSUE THREAD

**Issue by ozanilbey** [pho-incubator/graphjs-server#9]
setProfile requires a unique username, which makes it impossible to update when the username is sent unchanged (same as before).

**Comment by esokullu** [comment]
I don't believe it does require. Please test again.

**Comment by ozanilbey** [comment]
I tested this for an existing username (emresokullu): http://phonetworks.com:1338/setProfile?avatar=http://www.emresokullu.com/assets/images/picture.jpg&birthday=01/01/1980&about=Hello&username=emresokullu&emre@emre.com&public_id=16D58CF2-FD88-4A49-972B-6F60054BF023

The response is like this: Given field (Username) is not unique with the value (emresokullu)

It won't set until new username is something not registered. So this works (emresokullu2): http://phonetworks.com:1338/setProfile?avatar=http://www.emresokullu.com/assets/images/picture.jpg&birthday=01/01/1980&about=Hello&username=emresokullu2&emre@emre.com&public_id=16D58CF2-FD88-4A49-972B-6F60054BF023

**Comment by ozanilbey** [comment]
But it will not work again because I just registered the username **emresokullu2**.

**Comment by esokullu** [comment]
@ozanilbey what if you do it one by one?
http://phonetworks.com:1338/setProfile?avatar=http://www.emresokullu.com/assets/images/picture.jpg

only. It works. Why do you enter them all?

**Comment by ozanilbey** [comment]
How can I possibly change the username with this method? http://phonetworks.com:1338/username=emresokullu ?

**Comment by ozanilbey** [comment]
Okay, got it. I will set email and username separately.
